export const en = {
  appName: 'CEV Maintenance',
  nav: { home: 'Home', work: 'Work', catalog: 'Catalog', maintenance: 'Maintenance', profile: 'Profile' },
  common: {
    childSubtitle: 'Lists and detailed information are managed here.', masterListSubtitle: 'Search, create and manage records by category.', search: 'Search by code, name, location, group, type...', total: 'Total', tapForDetail: 'Tap to view details', add: 'Add', edit: 'Edit', save: 'Save', active: 'In use', warning: 'Needs attention', inactive: 'Inactive', noResults: 'No matching records found', nextDue: 'Next due', stock: 'Stock', code: 'Code', name: 'Name', specification: 'Specification', location: 'Location', basicInfo: 'Basic information', relatedManagement: 'Related management', history: 'History', maintenancePlan: 'Maintenance plan', workOrders: 'Work orders', documents: 'Documents / records', createRecord: 'Create new record', editRecord: 'Edit record', requiredHint: 'Enter required information.', enterName: 'Enter name', enterSpecification: 'Enter specification', enterLocation: 'Enter location', controlInfo: 'Control information', qrAutoHint: 'A QR code is linked to this record for quick lookup.', historyAutoHint: 'Changes and maintenance activities are stored in history.', savedDemo: 'Draft UI saved',
    loadError: 'Unable to load data', saveError: 'Unable to save data', loading: 'Loading data...', nameRequired: 'Name is required.', groupRequired: 'Select an asset group.', typeRequired: 'Select an asset type.', assetClassification: 'Asset classification', assetGroup: 'Asset group', assetType: 'Asset type', parentAsset: 'Parent asset', parentLocation: 'Parent location', linkedAsset: 'Linked asset', currentValue: 'Current value', unit: 'Unit', meterType: 'Reading type', controlRules: 'Applicable controls', requiresQr: 'QR required', requiresMaintenance: 'Maintenance required', requiresPrestart: 'Pre-start check required', requiresCalibration: 'Calibration / verification required', tracksDowntime: 'Track downtime', usesSpareParts: 'Manage linked spare parts'
  },
  home: { title: 'Maintenance overview', subtitle: 'Track work, equipment and maintenance schedules in one place.', openWork: 'Open work', openWorkNote: '3 high-priority tasks', overdue: 'Overdue', overdueNote: 'Needs action today', pmToday: 'Maintenance today', pmTodayNote: '2 tasks completed', stoppedEquipment: 'Stopped equipment', stoppedEquipmentNote: 'Press machine PR-03', attention: 'Work requiring attention', task1: 'Check abnormal noise', task2: 'Replace air filter periodically', task3: 'Check oil leakage', asset1: 'Stamping machine ST-02', asset2: 'Air compressor AC-01', asset3: 'Press machine PR-03' },
  catalog: {
    title: 'Management catalog', subtitle: 'Keep a small set of top-level CMMS masters; classify every machine and managed object inside Assets.', principleTitle: 'One asset master', principleText: 'Production machines, jigs, gauges, computers, Wi-Fi, plant lighting and forklifts are all Assets. Group and type determine the controls.',
    assets: 'Assets', assetsNote: 'One TS code family for all assets, with group, type and parent/child hierarchy.', locations: 'Locations', locationsNote: 'Independent location tree: plant, area, line, room, warehouse and sub-location.', inventory: 'Parts & inventory', inventoryNote: 'Spare parts, consumables, stock by location and cycle counts.', meters: 'Meters', metersNote: 'Operating hours, cycles, km or readings used to trigger maintenance.', peopleGroups: 'People & teams', peopleGroupsNote: 'Users, roles and work teams.', partners: 'Suppliers & customers', partnersNote: 'Service providers, calibration/repair vendors and customers.', assetTypes: 'Asset groups / types', assetTypesNote: 'Add, rename or retire asset types without changing application code.', commonProcesses: 'Common processes', commonProcessesText: 'Issue reporting • Preventive maintenance • Inspection • Parts • Movement • Calibration • History'
  },
  catalogHub: {
    subtitle: 'Related functions are grouped together so the top-level catalog stays compact.', spareParts: 'Spare parts', sparePartsNote: 'Part codes, inventory and asset relationships.', consumables: 'Maintenance consumables', consumablesNote: 'Oil, grease, filters, chemicals and consumable materials.', cycleCounts: 'Cycle counts', cycleCountsNote: 'Create a count, compare physical stock and resolve variances.', users: 'Users', usersNote: 'Accounts, roles and application permissions.', teams: 'Teams', teamsNote: 'Maintenance, production, quality, warehouse or other work teams.', suppliers: 'Suppliers', suppliersNote: 'Calibration, repair and outsourced service providers.', customers: 'Customers', customersNote: 'Customers linked to specific requirements and assets/tooling.', inventoryRuleTitle: 'Inventory by location', inventoryRuleText: 'One part has one master code but can be stocked at multiple locations. Cycle count is an inventory workflow, not an asset type.'
  },
  work: { title: 'Maintenance work', subtitle: 'Manage requests, work orders and execution history', repairRequest: 'Repair requests', openOrders: 'Open work orders', mine: 'My work', overdue: 'Overdue work', completed: 'Completed work' },
  maintenance: { title: 'Preventive maintenance', subtitle: 'Plans, schedules and inspection checklists', today: 'Maintenance today', thisWeek: 'This week plan', upcoming: 'Upcoming due', checklist: 'Inspection checklists', history: 'Maintenance history' },
  profile: { title: 'Profile', subtitle: 'Account and application settings', account: 'Personal profile', notifications: 'Notifications', settings: 'Settings', logout: 'Sign out' },
  settings: { title: 'Settings', subtitle: 'Customize the application for your work', language: 'Language', languageDescription: 'Select the display language', vietnamese: 'Vietnamese', english: 'English', korean: 'Korean', comingSoon: 'Coming soon' },
} as const;
