export const ko = {
  appName: 'CEV 유지보수',
  nav: { home: '홈', work: '작업', catalog: '관리항목', maintenance: '유지보수', profile: '내 정보' },
  common: {
    childSubtitle: '목록과 상세 정보를 여기에서 관리합니다.', masterListSubtitle: '항목별로 검색, 신규 등록 및 이력 관리를 수행합니다.', search: '코드, 이름, 위치, 그룹, 유형으로 검색...', total: '총계', tapForDetail: '눌러서 상세보기', add: '추가', edit: '수정', save: '저장', active: '사용 중', warning: '주의 필요', inactive: '사용 중지', noResults: '일치하는 데이터가 없습니다', nextDue: '다음 예정일', stock: '재고', code: '코드', name: '이름', specification: '규격 / 사양', location: '위치', basicInfo: '기본 정보', relatedManagement: '연관 관리', history: '이력', maintenancePlan: '보전 계획', workOrders: '작업지시', documents: '문서 / 기록', createRecord: '신규 등록', editRecord: '정보 수정', requiredHint: '필수 정보를 입력하세요.', enterName: '이름 입력', enterSpecification: '규격 또는 사양 입력', enterLocation: '위치 입력', controlInfo: '관리 정보', qrAutoHint: '빠른 조회를 위해 QR 코드가 이 항목과 연결됩니다.', historyAutoHint: '변경 및 유지보수 활동은 이력에 저장됩니다.', savedDemo: '화면 초안이 저장되었습니다',
    loadError: '데이터를 불러올 수 없습니다', saveError: '데이터를 저장할 수 없습니다', loading: '데이터 불러오는 중...', nameRequired: '이름은 필수입니다.', groupRequired: '자산 그룹을 선택하세요.', typeRequired: '자산 유형을 선택하세요.', assetClassification: '자산 분류', assetGroup: '자산 그룹', assetType: '자산 유형', parentAsset: '상위 자산', parentLocation: '상위 위치', linkedAsset: '연결 자산', currentValue: '현재 값', unit: '단위', meterType: '지표 유형', controlRules: '적용 관리 규칙', requiresQr: 'QR 필요', requiresMaintenance: '유지보수 필요', requiresPrestart: '운전 전 점검 필요', requiresCalibration: '교정 / 검증 필요', tracksDowntime: '정지시간 추적', usesSpareParts: '연결 예비품 관리'
  },
  home: { title: '유지보수 현황', subtitle: '작업, 설비 및 유지보수 일정을 한곳에서 관리합니다.', openWork: '진행 중 작업', openWorkNote: '높은 우선순위 작업 3건', overdue: '기한 초과', overdueNote: '오늘 조치 필요', pmToday: '오늘 보전', pmTodayNote: '2건 완료', stoppedEquipment: '정지 설비', stoppedEquipmentNote: '프레스 PR-03', attention: '주의가 필요한 작업', task1: '이상 소음 점검', task2: '에어 필터 정기 교체', task3: '오일 누유 점검', asset1: '프레스 설비 ST-02', asset2: '에어 컴프레서 AC-01', asset3: '프레스 PR-03' },
  catalog: {
    title: '관리 항목', subtitle: '대형 CMMS처럼 상위 관리항목은 적게 유지하고, 모든 기계와 관리대상은 자산 내부에서 분류합니다.', principleTitle: '하나의 자산 원장', principleText: '생산설비, 지그, 측정기, 컴퓨터, Wi-Fi, 공장 조명, 지게차 모두 자산입니다. 그룹과 유형에 따라 관리 규칙이 결정됩니다.',
    assets: '자산', assetsNote: '모든 자산은 TS 코드 체계를 사용하며 그룹, 유형, 상하위 구조를 지원합니다.', locations: '위치', locationsNote: '공장, 구역, 라인, 방, 창고 및 하위 위치를 독립 트리로 관리합니다.', inventory: '부품 & 재고', inventoryNote: '예비품, 소모품, 위치별 재고 및 순환 실사.', meters: '운전 지표', metersNote: '가동시간, 사이클, 거리 또는 유지보수 조건용 계측값.', peopleGroups: '사용자 & 그룹', peopleGroupsNote: '사용자, 역할 및 작업 그룹.', partners: '공급업체 & 고객', partnersNote: '교정/수리 서비스 업체와 고객.', assetTypes: '자산 그룹 / 유형', assetTypesNote: '프로그램 수정 없이 자산 유형을 추가, 이름 변경 또는 사용중지할 수 있습니다.', commonProcesses: '공통 업무', commonProcessesText: '고장 신고 • 예방보전 • 점검 • 부품 • 이동 • 교정 • 이력'
  },
  catalogHub: {
    subtitle: '관련 기능을 묶어 상위 관리항목을 간결하게 유지합니다.', spareParts: '예비 부품', sparePartsNote: '부품 코드, 재고 및 자산 연결.', consumables: '유지보수 소모품', consumablesNote: '오일, 그리스, 필터, 화학품 및 소모품.', cycleCounts: '순환 실사', cycleCountsNote: '실사 계획, 실제 수량 비교 및 차이 처리.', users: '사용자', usersNote: '계정, 역할 및 시스템 권한.', teams: '그룹', teamsNote: '유지보수, 생산, 품질, 창고 등 작업 그룹.', suppliers: '공급업체', suppliersNote: '교정, 수리 및 외주 서비스 업체.', customers: '고객', customersNote: '고객 요구사항 및 자산/툴링과 연결되는 고객.', inventoryRuleTitle: '위치별 재고', inventoryRuleText: '하나의 부품은 하나의 기본 코드를 가지며 여러 위치에 재고를 둘 수 있습니다. 순환 실사는 자산 유형이 아니라 재고 업무입니다.'
  },
  work: { title: '유지보수 작업', subtitle: '요청, 작업지시 및 수행 이력을 관리합니다.', repairRequest: '수리 요청', openOrders: '진행 중 작업지시', mine: '내 작업', overdue: '기한 초과 작업', completed: '완료된 작업' },
  maintenance: { title: '예방보전', subtitle: '계획, 일정 및 점검 체크리스트를 관리합니다.', today: '오늘 보전', thisWeek: '이번 주 계획', upcoming: '예정 작업', checklist: '점검표 양식', history: '보전 이력' },
  profile: { title: '내 정보', subtitle: '계정 및 앱 설정', account: '개인 정보', notifications: '알림', settings: '설정', logout: '로그아웃' },
  settings: { title: '설정', subtitle: '업무 환경에 맞게 앱을 설정합니다.', language: '언어', languageDescription: '표시 언어를 선택하세요.', vietnamese: '베트남어', english: '영어', korean: '한국어', comingSoon: '준비 중' },
} as const;
