export const ko = {
  appName: 'CEV 유지보수',
  nav: { home: '홈', work: '작업', catalog: '관리항목', maintenance: '유지보수', profile: '내 정보' },
  common: {
    childSubtitle: '목록과 상세 정보를 여기에서 관리합니다.', masterListSubtitle: '항목별로 검색, 신규 등록 및 이력 관리를 수행합니다.', search: '코드, 이름, 위치로 검색...', total: '총계', tapForDetail: '눌러서 상세보기', add: '추가', edit: '수정', save: '저장', active: '사용 중', warning: '주의 필요', inactive: '사용 중지', noResults: '일치하는 데이터가 없습니다', nextDue: '다음 예정일', stock: '재고', code: '코드', name: '이름', specification: '규격 / 사양', location: '위치', basicInfo: '기본 정보', relatedManagement: '연관 관리', history: '이력', maintenancePlan: '보전 계획', workOrders: '작업지시', documents: '문서 / 기록', createRecord: '신규 등록', editRecord: '정보 수정', requiredHint: '필수 정보를 입력하세요. 항목별 전용 필드는 이후 확장할 수 있습니다.', enterName: '이름 입력', enterSpecification: '규격 또는 사양 입력', enterLocation: '위치 입력', controlInfo: '관리 정보', qrAutoHint: '모바일에서 빠르게 조회할 수 있도록 QR 코드가 이 항목과 연결됩니다.', historyAutoHint: '모든 변경 및 유지보수 활동은 이력에 자동 저장됩니다.', savedDemo: '화면 초안이 저장되었습니다' },
  home: { title: '유지보수 현황', subtitle: '작업, 설비 및 유지보수 일정을 한곳에서 관리합니다.', openWork: '진행 중 작업', openWorkNote: '높은 우선순위 작업 3건', overdue: '기한 초과', overdueNote: '오늘 조치 필요', pmToday: '오늘 예방보전', pmTodayNote: '2건 완료', stoppedEquipment: '정지 설비', stoppedEquipmentNote: '프레스 PR-03', attention: '주의가 필요한 작업', task1: '이상 소음 점검', task2: '에어 필터 정기 교체', task3: '오일 누유 점검', asset1: '프레스 설비 ST-02', asset2: '에어 컴프레서 AC-01', asset3: '프레스 PR-03' },
  catalog: { title: '관리 항목', subtitle: 'IATF 16949 유지보수 시스템에서 관리해야 하는 대상', assets: '생산 설비 및 기계', assetsNote: '프레스, 압착기, 권선기, 생산라인 및 생산설비', utilities: '유틸리티 및 기반시설', utilitiesNote: '에어 컴프레서, 칠러, 전기, 압축공기, 용수 및 공장 기반시설', tooling: '지그, 금형 및 공구', toolingNote: '지그, 픽스처, 금형, 게이지, 절삭공구 및 전용공구', measuring: '측정 및 검사 장비', measuringNote: '측정기, 검사장비, 교정 및 MSA 관리', spareParts: '예비 부품', sparePartsNote: '예비 부품, 재고, 최소/최대 재고 및 적용 설비 관리', consumables: '유지보수 소모품', consumablesNote: '오일, 그리스, 필터, 세척제 및 기타 소모품', safety: '안전 장비', safetyNote: '안전 스위치, 라이트 커튼, 비상정지 및 설비 보호장치', suppliers: '서비스 공급업체', suppliersNote: '교정, 수리, 외주 유지보수 및 공급업체 능력 평가', commonProcesses: '공통 업무', commonProcessesText: '수리 요청 • 작업지시 • 예방보전 • 점검 • 고장 • 사용 부품 • 수리 후 확인 • 설비 이력' },
  work: { title: '유지보수 작업', subtitle: '요청, 작업지시 및 수행 이력을 관리합니다.', repairRequest: '수리 요청', openOrders: '진행 중 작업지시', mine: '내 작업', overdue: '기한 초과 작업', completed: '완료된 작업' },
  maintenance: { title: '예방보전', subtitle: '계획, 일정 및 점검 체크리스트를 관리합니다.', today: '오늘 보전', thisWeek: '이번 주 계획', upcoming: '예정 작업', checklist: '점검표 양식', history: '보전 이력' },
  profile: { title: '내 정보', subtitle: '계정 및 앱 설정', account: '개인 정보', notifications: '알림', settings: '설정', logout: '로그아웃' },
  settings: { title: '설정', subtitle: '업무 환경에 맞게 앱을 설정합니다.', language: '언어', languageDescription: '표시 언어를 선택하세요.', vietnamese: '베트남어', english: '영어', korean: '한국어', comingSoon: '준비 중' },
} as const;
