export const vi = {
  appName: 'CEV Bảo trì',
  nav: { home: 'Trang chủ', work: 'Công việc', catalog: 'Danh mục', maintenance: 'Bảo trì', profile: 'Cá nhân' },
  common: {
    childSubtitle: 'Danh sách và thông tin chi tiết sẽ được quản lý tại đây.', masterListSubtitle: 'Tra cứu, thêm mới và quản lý hồ sơ theo từng danh mục.', search: 'Tìm theo mã, tên, vị trí, nhóm, loại...', total: 'Tổng số', tapForDetail: 'Chạm để xem chi tiết', add: 'Thêm mới', edit: 'Chỉnh sửa', save: 'Lưu', active: 'Đang sử dụng', warning: 'Cần chú ý', inactive: 'Ngừng sử dụng', noResults: 'Không tìm thấy dữ liệu phù hợp', nextDue: 'Hạn tiếp theo', stock: 'Tồn kho', code: 'Mã', name: 'Tên', specification: 'Quy cách / thông số', location: 'Vị trí', basicInfo: 'Thông tin cơ bản', relatedManagement: 'Quản lý liên quan', history: 'Lịch sử', maintenancePlan: 'Kế hoạch bảo trì', workOrders: 'Lệnh bảo trì', documents: 'Tài liệu / hồ sơ', createRecord: 'Tạo hồ sơ mới', editRecord: 'Chỉnh sửa hồ sơ', requiredHint: 'Nhập thông tin cần thiết.', enterName: 'Nhập tên', enterSpecification: 'Nhập quy cách hoặc thông số', enterLocation: 'Nhập vị trí', controlInfo: 'Thông tin kiểm soát', qrAutoHint: 'Mã QR được liên kết với hồ sơ để tra cứu nhanh.', historyAutoHint: 'Mọi thay đổi và hoạt động bảo trì được lưu vào lịch sử.', savedDemo: 'Đã lưu bản nháp giao diện',
    loadError: 'Không thể tải dữ liệu', saveError: 'Không thể lưu dữ liệu', loading: 'Đang tải dữ liệu...', nameRequired: 'Tên là thông tin bắt buộc.', groupRequired: 'Phải chọn nhóm tài sản.', typeRequired: 'Phải chọn loại tài sản.', assetClassification: 'Phân loại tài sản', assetGroup: 'Nhóm tài sản', assetType: 'Loại tài sản', parentAsset: 'Tài sản cha', parentLocation: 'Vị trí cha', linkedAsset: 'Tài sản liên kết', currentValue: 'Giá trị hiện tại', unit: 'Đơn vị', meterType: 'Loại chỉ số', controlRules: 'Quy tắc áp dụng', requiresQr: 'Cần mã QR', requiresMaintenance: 'Cần bảo trì', requiresPrestart: 'Cần kiểm tra trước vận hành', requiresCalibration: 'Cần hiệu chuẩn / kiểm tra xác nhận', tracksDowntime: 'Theo dõi thời gian dừng', usesSpareParts: 'Quản lý phụ tùng liên quan'
  },
  home: { title: 'Tổng quan bảo trì', subtitle: 'Theo dõi công việc, thiết bị và lịch bảo trì trong một nơi.', openWork: 'Công việc mở', openWorkNote: '3 việc ưu tiên cao', overdue: 'Quá hạn', overdueNote: 'Cần xử lý hôm nay', pmToday: 'Bảo trì hôm nay', pmTodayNote: '2 việc đã hoàn thành', stoppedEquipment: 'Thiết bị dừng', stoppedEquipmentNote: 'Máy ép PR-03', attention: 'Công việc cần chú ý', task1: 'Kiểm tra tiếng ồn bất thường', task2: 'Thay lọc khí định kỳ', task3: 'Kiểm tra rò dầu', asset1: 'Máy dập ST-02', asset2: 'Máy nén khí AC-01', asset3: 'Máy ép PR-03' },
  catalog: {
    title: 'Danh mục quản lý', subtitle: 'Giữ ít danh mục gốc như các hệ thống CMMS lớn; mọi loại máy và vật thể được phân loại bên trong Tài sản.', principleTitle: 'Một kho tài sản gốc', principleText: 'Máy sản xuất, jig, thiết bị đo, máy tính, Wi-Fi, đèn nhà xưởng, xe nâng… đều là Tài sản. Nhóm và loại quyết định quy tắc áp dụng.',
    assets: 'Tài sản', assetsNote: 'Một mã TS cho mọi tài sản; hỗ trợ nhóm, loại và quan hệ cha/con.', locations: 'Vị trí', locationsNote: 'Cây vị trí độc lập: nhà máy, khu, line, phòng, kho và vị trí con.', inventory: 'Phụ tùng & kho', inventoryNote: 'Phụ tùng, vật tư, tồn theo vị trí và kiểm kê chu kỳ.', meters: 'Đồng hồ theo dõi', metersNote: 'Giờ chạy, chu kỳ, km hoặc thông số để kích hoạt bảo trì.', peopleGroups: 'Người & nhóm', peopleGroupsNote: 'Người dùng, vai trò và nhóm thực hiện công việc.', partners: 'Nhà cung cấp & khách hàng', partnersNote: 'Đối tác dịch vụ, hiệu chuẩn, sửa chữa và khách hàng.', assetTypes: 'Nhóm / loại tài sản', assetTypesNote: 'Thêm, đổi tên hoặc ngừng dùng loại tài sản mà không phải sửa chương trình.', commonProcesses: 'Nghiệp vụ dùng chung', commonProcessesText: 'Báo sự cố • Bảo trì định kỳ • Kiểm tra • Phụ tùng • Di chuyển • Hiệu chuẩn • Lịch sử'
  },
  catalogHub: {
    subtitle: 'Các chức năng liên quan được gom chung để danh mục cấp cao luôn gọn.', spareParts: 'Phụ tùng thay thế', sparePartsNote: 'Mã phụ tùng, tồn kho và liên kết với tài sản.', consumables: 'Vật tư bảo trì', consumablesNote: 'Dầu, mỡ, lọc, hóa chất và vật tư tiêu hao.', cycleCounts: 'Kiểm kê chu kỳ', cycleCountsNote: 'Lập đợt đếm, so sánh số thực tế và xử lý chênh lệch.', users: 'Người dùng', usersNote: 'Tài khoản, vai trò và quyền sử dụng hệ thống.', teams: 'Nhóm', teamsNote: 'Nhóm bảo trì, sản xuất, QC, kho hoặc nhóm công việc khác.', suppliers: 'Nhà cung cấp', suppliersNote: 'Đơn vị hiệu chuẩn, sửa chữa và dịch vụ thuê ngoài.', customers: 'Khách hàng', customersNote: 'Khách hàng liên quan đến yêu cầu riêng và tài sản/tooling.', inventoryRuleTitle: 'Tồn kho theo vị trí', inventoryRuleText: 'Một phụ tùng có một mã gốc nhưng có thể tồn ở nhiều vị trí. Kiểm kê chu kỳ là nghiệp vụ kho, không phải một loại tài sản.'
  },
  work: { title: 'Công việc bảo trì', subtitle: 'Quản lý yêu cầu, lệnh bảo trì và lịch sử thực hiện', repairRequest: 'Yêu cầu sửa chữa', openOrders: 'Lệnh bảo trì đang mở', mine: 'Công việc của tôi', overdue: 'Công việc quá hạn', completed: 'Công việc đã hoàn thành' },
  maintenance: { title: 'Bảo trì định kỳ', subtitle: 'Kế hoạch, lịch thực hiện và biểu mẫu kiểm tra', today: 'Bảo trì hôm nay', thisWeek: 'Kế hoạch tuần này', upcoming: 'Sắp đến hạn', checklist: 'Biểu mẫu kiểm tra', history: 'Lịch sử bảo trì' },
  profile: { title: 'Cá nhân', subtitle: 'Tài khoản và cài đặt ứng dụng', account: 'Hồ sơ cá nhân', notifications: 'Thông báo', settings: 'Cài đặt', logout: 'Đăng xuất' },
  settings: { title: 'Cài đặt', subtitle: 'Tùy chỉnh ứng dụng theo nhu cầu công việc', language: 'Ngôn ngữ', languageDescription: 'Chọn ngôn ngữ hiển thị', vietnamese: 'Tiếng Việt', english: 'Tiếng Anh', korean: 'Tiếng Hàn', comingSoon: 'Sẽ bổ sung' },
} as const;
export type ViDictionary = typeof vi;
