export const vi = {
  appName: 'CEV Bảo trì',
  nav: { home: 'Trang chủ', work: 'Công việc', catalog: 'Danh mục', maintenance: 'Bảo trì', profile: 'Cá nhân' },
  common: { childSubtitle: 'Danh sách và thông tin chi tiết sẽ được quản lý tại đây.' },
  home: { title: 'Tổng quan bảo trì', subtitle: 'Theo dõi công việc, thiết bị và lịch bảo trì trong một nơi.', openWork: 'Công việc mở', openWorkNote: '3 việc ưu tiên cao', overdue: 'Quá hạn', overdueNote: 'Cần xử lý hôm nay', pmToday: 'PM hôm nay', pmTodayNote: '2 việc đã hoàn thành', stoppedEquipment: 'Thiết bị dừng', stoppedEquipmentNote: 'Máy ép PR-03', attention: 'Công việc cần chú ý', task1: 'Kiểm tra tiếng ồn bất thường', task2: 'Thay lọc khí định kỳ', task3: 'Kiểm tra rò dầu', asset1: 'Máy dập ST-02', asset2: 'Máy nén khí AC-01', asset3: 'Máy ép PR-03' },
  catalog: { title: 'Danh mục quản lý', subtitle: 'Các đối tượng cần kiểm soát trong hệ thống bảo trì theo IATF 16949', assets: 'Máy móc & thiết bị sản xuất', assetsNote: 'Máy dập, máy ép, máy quấn, dây chuyền và thiết bị sản xuất', utilities: 'Thiết bị phụ trợ & hạ tầng', utilitiesNote: 'Máy nén khí, chiller, điện, khí, nước và hạ tầng nhà máy', tooling: 'Đồ gá, khuôn & dụng cụ', toolingNote: 'Jig, fixture, khuôn, đồ gá, dao cụ và dụng cụ chuyên dùng', measuring: 'Thiết bị đo & kiểm tra', measuringNote: 'Dụng cụ đo, thiết bị kiểm tra, hiệu chuẩn và MSA', spareParts: 'Phụ tùng thay thế', sparePartsNote: 'Linh kiện dự phòng, tồn kho, mức tối thiểu/tối đa và thiết bị sử dụng', consumables: 'Vật tư bảo trì', consumablesNote: 'Dầu, mỡ, lọc, hóa chất vệ sinh và vật tư tiêu hao', safety: 'Thiết bị an toàn', safetyNote: 'Công tắc an toàn, rèm quang, dừng khẩn và thiết bị bảo vệ máy', suppliers: 'Nhà cung cấp dịch vụ', suppliersNote: 'Đơn vị hiệu chuẩn, sửa chữa, bảo trì thuê ngoài và đánh giá năng lực', commonProcesses: 'Nghiệp vụ dùng chung', commonProcessesText: 'Yêu cầu sửa chữa • Lệnh bảo trì • Bảo trì định kỳ • Kiểm tra • Sự cố • Phụ tùng sử dụng • Xác nhận sau sửa chữa • Lịch sử thiết bị' },
  work: { title: 'Công việc bảo trì', subtitle: 'Quản lý yêu cầu, lệnh bảo trì và lịch sử thực hiện', repairRequest: 'Yêu cầu sửa chữa', openOrders: 'Lệnh bảo trì đang mở', mine: 'Công việc của tôi', overdue: 'Công việc quá hạn', completed: 'Công việc đã hoàn thành' },
  maintenance: { title: 'Bảo trì định kỳ', subtitle: 'Kế hoạch, lịch thực hiện và biểu mẫu kiểm tra', today: 'Bảo trì hôm nay', thisWeek: 'Kế hoạch tuần này', upcoming: 'Sắp đến hạn', checklist: 'Biểu mẫu kiểm tra', history: 'Lịch sử bảo trì' },
  profile: { title: 'Cá nhân', subtitle: 'Tài khoản và cài đặt ứng dụng', account: 'Hồ sơ cá nhân', notifications: 'Thông báo', settings: 'Cài đặt', logout: 'Đăng xuất' },
  settings: { title: 'Cài đặt', subtitle: 'Tùy chỉnh ứng dụng theo nhu cầu công việc', language: 'Ngôn ngữ', languageDescription: 'Chọn ngôn ngữ hiển thị', vietnamese: 'Tiếng Việt', english: 'Tiếng Anh', korean: 'Tiếng Hàn', comingSoon: 'Sẽ bổ sung' },
} as const;
export type ViDictionary = typeof vi;
