import { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Alert, Modal, ScrollView, StyleSheet, Switch, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { colors } from '../theme/colors';
import type { Locale } from '../i18n';
import { getAssetCatalogUi } from '../i18n/assetCatalogUi';
import type { AssetControlFlags } from '../data/masterData';
import { createAssetGroup, createAssetType, deleteAssetGroupSafely, deleteAssetTypeSafely, listAssetGroupsAdmin, listAssetTypesAdmin, reorderAssetGroups, reorderAssetTypes, setAssetGroupActive, setAssetTypeActive, updateAssetGroup, updateAssetType, type AssetGroupAdminRecord, type AssetTypeAdminRecord } from '../data/assetCatalogRepository';

type Props={locale?:Locale;onBack:()=>void};
type Editor={kind:'group'|'type';record?:AssetGroupAdminRecord|AssetTypeAdminRecord}|null;
const emptyFlags:AssetControlFlags={requiresQr:true,requiresMaintenance:false,requiresPrestart:false,requiresCalibration:false,tracksDowntime:false,usesSpareParts:false};

export function AssetCatalogAdminScreen({locale='vi',onBack}:Props){
  const t=getAssetCatalogUi(locale);
  const[groups,setGroups]=useState<AssetGroupAdminRecord[]>([]); const[types,setTypes]=useState<AssetTypeAdminRecord[]>([]);
  const[selected,setSelected]=useState<string>(); const[search,setSearch]=useState(''); const[loading,setLoading]=useState(true);
  const[editor,setEditor]=useState<Editor>(null); const[name,setName]=useState(''); const[description,setDescription]=useState(''); const[flags,setFlags]=useState<AssetControlFlags>(emptyFlags);
  const current=groups.find(g=>g.id===selected);
  const loadGroups=async()=>{setLoading(true);try{const rows=await listAssetGroupsAdmin();setGroups(rows);setSelected(v=>v&&rows.some(r=>r.id===v)?v:rows[0]?.id);}catch(e:any){Alert.alert(t.error,e?.message??String(e));}finally{setLoading(false);}};
  const loadTypes=async(id?:string)=>{if(!id){setTypes([]);return;}try{setTypes(await listAssetTypesAdmin(id));}catch(e:any){Alert.alert(t.error,e?.message??String(e));}};
  useEffect(()=>{void loadGroups();},[]); useEffect(()=>{void loadTypes(selected);},[selected]);
  const visibleGroups=useMemo(()=>groups.filter(g=>`${g.name} ${g.description}`.toLowerCase().includes(search.toLowerCase())),[groups,search]);
  const visibleTypes=useMemo(()=>types.filter(x=>`${x.name} ${x.description}`.toLowerCase().includes(search.toLowerCase())),[types,search]);
  const open=(kind:'group'|'type',record?:AssetGroupAdminRecord|AssetTypeAdminRecord)=>{setEditor({kind,record});setName(record?.name??'');setDescription(record?.description??'');setFlags(kind==='type'&&record?(record as AssetTypeAdminRecord).flags:emptyFlags);};
  const save=async()=>{if(!name.trim())return;try{if(editor?.kind==='group'){if(editor.record)await updateAssetGroup(editor.record.id,{name,description});else await createAssetGroup({name,description});await loadGroups();}else if(editor?.kind==='type'&&selected){if(editor.record)await updateAssetType(editor.record.id,{groupId:selected,name,description,flags});else await createAssetType({groupId:selected,name,description,flags});await loadTypes(selected);await loadGroups();}setEditor(null);}catch(e:any){Alert.alert(t.error,e?.message??String(e));}};
  const remove=async(kind:'group'|'type',id:string)=>{try{const r=kind==='group'?await deleteAssetGroupSafely(id):await deleteAssetTypeSafely(id);if(!r.deleted){Alert.alert(t.deleteBlocked,`${r.references}`);return;}if(kind==='group')await loadGroups();else{await loadTypes(selected);await loadGroups();}}catch(e:any){Alert.alert(t.error,e?.message??String(e));}};
  const move=async(kind:'group'|'type',id:string,delta:number)=>{const rows=kind==='group'?groups:types;const i=rows.findIndex(r=>r.id===id);const j=i+delta;if(i<0||j<0||j>=rows.length)return;const ids=rows.map(r=>r.id);[ids[i],ids[j]]=[ids[j],ids[i]];try{if(kind==='group'){await reorderAssetGroups(ids);await loadGroups();}else{await reorderAssetTypes(ids);await loadTypes(selected);}}catch(e:any){Alert.alert(t.error,e?.message??String(e));}};
  const Row=({kind,record,index,total}:{kind:'group'|'type';record:AssetGroupAdminRecord|AssetTypeAdminRecord;index:number;total:number})=><View style={[s.card,!record.active&&s.inactive]}><TouchableOpacity style={{flex:1}} onPress={()=>kind==='group'&&setSelected(record.id)}><View style={s.rowTitle}><Text style={s.cardTitle}>{record.name}</Text><Text style={s.badge}>{record.active?t.active:t.inactive}</Text></View><Text style={s.note}>{record.description||'—'}</Text><Text style={s.meta}>{kind==='group'?`${(record as AssetGroupAdminRecord).typeCount} ${t.types} · ${(record as AssetGroupAdminRecord).assetCount} assets`:`${(record as AssetTypeAdminRecord).assetCount} assets`}</Text></TouchableOpacity><View style={s.actions}><TouchableOpacity onPress={()=>void move(kind,record.id,-1)} disabled={index===0}><Ionicons name="chevron-up" size={19} color={colors.muted}/></TouchableOpacity><TouchableOpacity onPress={()=>void move(kind,record.id,1)} disabled={index===total-1}><Ionicons name="chevron-down" size={19} color={colors.muted}/></TouchableOpacity><TouchableOpacity onPress={()=>open(kind,record)}><Ionicons name="create-outline" size={19} color={colors.primary}/></TouchableOpacity><TouchableOpacity onPress={()=>void(kind==='group'?setAssetGroupActive(record.id,!record.active).then(loadGroups):setAssetTypeActive(record.id,!record.active).then(()=>loadTypes(selected)))}><Ionicons name={record.active?'pause-circle-outline':'play-circle-outline'} size={20} color={colors.muted}/></TouchableOpacity><TouchableOpacity onPress={()=>Alert.alert(t.delete,t.confirmDelete,[{text:t.cancel,style:'cancel'},{text:t.delete,style:'destructive',onPress:()=>void remove(kind,record.id)}])}><Ionicons name="trash-outline" size={19} color="#b42318"/></TouchableOpacity></View></View>;
  return <View style={s.page}><View style={s.header}><TouchableOpacity onPress={onBack}><Ionicons name="chevron-back" size={24} color={colors.text}/></TouchableOpacity><View style={{flex:1}}><Text style={s.title}>{t.title}</Text><Text style={s.subtitle}>{t.subtitle}</Text></View></View><View style={s.search}><Ionicons name="search" size={18} color={colors.muted}/><TextInput value={search} onChangeText={setSearch} placeholder={t.search} placeholderTextColor={colors.muted} style={{flex:1,color:colors.text}}/></View>{loading?<ActivityIndicator style={{marginTop:40}} color={colors.primary}/>:<ScrollView contentContainerStyle={s.content}><View style={s.sectionHead}><Text style={s.sectionTitle}>{t.groups}</Text><TouchableOpacity style={s.add} onPress={()=>open('group')}><Ionicons name="add" size={18} color="#fff"/><Text style={s.addText}>{t.addGroup}</Text></TouchableOpacity></View>{visibleGroups.map(r=><Row key={r.id} kind="group" record={r} index={groups.findIndex(g=>g.id===r.id)} total={groups.length}/>)}{!visibleGroups.length&&<Text style={s.empty}>{t.noGroups}</Text>}<View style={[s.sectionHead,{marginTop:22}]}><View><Text style={s.sectionTitle}>{t.types}</Text><Text style={s.note}>{current?.name??t.selectGroup}</Text></View><TouchableOpacity disabled={!selected} style={[s.add,!selected&&{opacity:.4}]} onPress={()=>open('type')}><Ionicons name="add" size={18} color="#fff"/><Text style={s.addText}>{t.addType}</Text></TouchableOpacity></View>{visibleTypes.map(r=><Row key={r.id} kind="type" record={r} index={types.findIndex(x=>x.id===r.id)} total={types.length}/>)}{selected&&!visibleTypes.length&&<Text style={s.empty}>{t.noTypes}</Text>}</ScrollView>}<Modal visible={Boolean(editor)} transparent animationType="slide" onRequestClose={()=>setEditor(null)}><View style={s.overlay}><View style={s.sheet}><Text style={s.sectionTitle}>{editor?.kind==='group'?t.group:t.type}</Text><Text style={s.label}>{t.name}</Text><TextInput value={name} onChangeText={setName} style={s.input}/><Text style={s.label}>{t.description}</Text><TextInput value={description} onChangeText={setDescription} multiline style={[s.input,{minHeight:76}]}/>{editor?.kind==='type'&&<View><Text style={s.label}>{t.flags}</Text>{([['requiresQr',t.qr],['requiresMaintenance',t.maintenance],['requiresPrestart',t.prestart],['requiresCalibration',t.calibration],['tracksDowntime',t.downtime],['usesSpareParts',t.spareParts]] as const).map(([key,label])=><View key={key} style={s.flag}><Text style={s.cardTitle}>{label}</Text><Switch value={Boolean(flags[key])} onValueChange={v=>setFlags(f=>({...f,[key]:v}))}/></View>)}</View>}<View style={s.footer}><TouchableOpacity onPress={()=>setEditor(null)} style={s.cancel}><Text>{t.cancel}</Text></TouchableOpacity><TouchableOpacity onPress={()=>void save()} style={s.save}><Text style={s.addText}>{t.save}</Text></TouchableOpacity></View></View></View></Modal></View>;
}

const s=StyleSheet.create({page:{flex:1,backgroundColor:colors.background},header:{flexDirection:'row',gap:10,padding:16,paddingTop:12,alignItems:'flex-start'},title:{fontSize:22,fontWeight:'900',color:colors.text},subtitle:{fontSize:12,lineHeight:17,color:colors.muted,marginTop:3},search:{marginHorizontal:16,marginBottom:8,height:44,borderWidth:1,borderColor:colors.border,borderRadius:12,backgroundColor:colors.surface,flexDirection:'row',alignItems:'center',gap:8,paddingHorizontal:12},content:{padding:16,paddingTop:8,paddingBottom:120,gap:9},sectionHead:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:12},sectionTitle:{fontSize:17,fontWeight:'900',color:colors.text},add:{height:36,borderRadius:10,paddingHorizontal:11,backgroundColor:colors.primary,flexDirection:'row',gap:5,alignItems:'center'},addText:{color:'#fff',fontWeight:'800'},card:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:14,padding:12,flexDirection:'row',gap:9},inactive:{opacity:.62},rowTitle:{flexDirection:'row',alignItems:'center',gap:8},cardTitle:{fontSize:14,fontWeight:'800',color:colors.text},badge:{fontSize:10,fontWeight:'800',color:colors.primary},note:{fontSize:12,lineHeight:17,color:colors.muted,marginTop:3},meta:{fontSize:11,color:colors.muted,marginTop:6},actions:{width:56,flexDirection:'row',flexWrap:'wrap',gap:8,justifyContent:'flex-end',alignContent:'center'},empty:{padding:16,textAlign:'center',color:colors.muted},overlay:{flex:1,justifyContent:'flex-end',backgroundColor:'rgba(0,0,0,.35)'},sheet:{backgroundColor:colors.surface,borderTopLeftRadius:22,borderTopRightRadius:22,padding:18,paddingBottom:30,maxHeight:'88%'},label:{fontSize:12,fontWeight:'800',color:colors.text,marginTop:13,marginBottom:6},input:{borderWidth:1,borderColor:colors.border,borderRadius:11,paddingHorizontal:12,paddingVertical:10,color:colors.text,backgroundColor:colors.background},flag:{height:42,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},footer:{flexDirection:'row',justifyContent:'flex-end',gap:9,marginTop:18},cancel:{height:42,paddingHorizontal:16,borderRadius:11,borderWidth:1,borderColor:colors.border,alignItems:'center',justifyContent:'center'},save:{height:42,paddingHorizontal:20,borderRadius:11,backgroundColor:colors.primary,alignItems:'center',justifyContent:'center'}});
